example.spring.application.name=NOMBRE_PROYECTO

# Importar las configuraciones fragmentadas
example.spring.config.import=classpath:application-bd.properties, classpath:application-jwt.properties

example.server.port=PUERTO