# ==========================================
# CREDENCIALES DE POSTGRESQL
# ==========================================
example.spring.datasource.url=jdbc:postgresql://localhost:5432/ejemplo_db
example.spring.datasource.username=TU_USUARIO
example.spring.datasource.password=TU_CONTRASEÑA
example.spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# COMPORTAMIENTO DE HIBERNATE
# ==========================================
example.spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola el SQL que Spring ejecuta por debajo (util para debug)
example.spring.jpa.show-sql=true
example.spring.jpa.properties.hibernate.format_sql=true